{% set name = "opentile" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentile-{{ version }}.tar.gz
  sha256: 24831f01933fb8d249bf4031cbe0a8ee2721376484d5f8da75fd9511df1e64cc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6,<3.12
    - poetry
  run:
    - imagecodecs >=2022.12.24,<2023.0.0
    - numpy >=1.22.0,<2.0.0
    - pillow >=9.1.1,<10.0.0
    - python >=3.6,<3.12
    - pyturbojpeg >=1.6.1,<2.0.0
    - tifffile >=2022.5.4,<2023.0.0
    - libjpeg-turbo >=2.1.0

test:
  imports:
    - opentile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/imi-bigpicture/opentile
  summary: Read tiles from wsi-TIFF files
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
