{% set name = "opentile" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentile-{{ version }}.tar.gz
  sha256: 93f22b9a69d9dfa1f2e10a0035fbe0ac9f79affed9f89e36be8389b66b3c33a0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
    - hatchling
  run:
    - python >={{ python_min }}
    - numpy >=1.22.0
    - imagecodecs >=2022.12.24
    - tifffile >=2022.5.4
    - pillow >=10.1.0
    - pyturbojpeg >=1.7.3,<2.0.0
    - cachetools >=5.0.0
    - defusedxml >=0.7.1
    - fsspec >=2024.2.0
    - ome-types >=0.5.0
    - universal-pathlib >=0.2.1

test:
  imports:
    - opentile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/imi-bigpicture/opentile
  summary: Read tiles from wsi-TIFF files
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
