{% set name = "opentile" %}
{% set version = "0.20.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentile-{{ version }}.tar.gz
  sha256: 4f7437efae727bc806721f0b753bb1bb2ceebeee8c771d6943e2b3e9ac492836

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
    - hatchling
  run:
    - imagecodecs >=2022.12.24
    - numpy >=1.22.0,<2.0.0
    - pillow >=10.1.0,<11.0.0
    - python >={{ python_min }},<3.12
    - pyturbojpeg >=1.7.3,<2.0.0
    - tifffile >=2022.5.4,<2023.0.0
    - libjpeg-turbo ==3.0.0
    - ome-types >=0.5.0,<0.6.0
    - defusedxml >=0.7.1,<0.8.0
    - libtiff ==4.6.0
    - libdeflate >=1.19
    - universal_pathlib 0.2.1,<0.3.0
    - fsspec >=2024.2.0,<2025.0.0

test:
  imports:
    - opentile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/imi-bigpicture/opentile
  summary: Read tiles from wsi-TIFF files
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
