{% set name = "opentile" %}
{% set version = "0.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opentile-{{ version }}.tar.gz
  sha256: 36f69a21e39f538aa11ad3dd9c2acc1cf5ba161560473879256c2189a04a2c3f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - imagecodecs >2023.9.4
    - numpy >=1.22.0,<2.0.0
    - pillow >=10.1.0,<11.0.0
    - python >={{ python_min }},<3.12
    - pyturbojpeg >=1.6.1,<2.0.0
    - tifffile >=2022.5.4,<2023.0.0
    - libjpeg-turbo ==3.0.0
    - ome-types <0.6.0,>=0.5.0
    - defusedxml >=0.7.1
    - libtiff ==4.6.0
    - libdeflate >=1.19,<1.20.0a0
    - universal_pathlib >=0.2.1
    - fsspec <2025.0.0,>=2024.2.0

test:
  imports:
    - opentile
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/imi-bigpicture/opentile
  summary: Read tiles from wsi-TIFF files
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
