{% set name = "opentile" %}
{% set version = "0.13.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/opentile-{{ version }}.tar.gz
  sha256: 7defe477b4f795557782d92a05d8679becf2684a121d469642c51352b3e6bc08

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9,<3.12
    - poetry
  run:
    - imagecodecs >2023.9.4
    - numpy >=1.22.0,<2.0.0
    - pillow >=10.1.0,<11.0.0
    - python >=3.6,<3.12
    - pyturbojpeg >=1.6.1,<2.0.0
    - tifffile >=2022.5.4,<2023.0.0
    - libjpeg-turbo ==3.0.0
    - ome-types >=0.4.0
    - defusedxml >=0.7.1
    - libtiff ==4.6.0
    - libdeflate >=1.19,<1.20.0a0
    - universal_pathlib >=0.2.1

test:
  imports:
    - opentile
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/imi-bigpicture/opentile
  summary: Read tiles from wsi-TIFF files
  license: Apache-2.0
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
